apiVersion: v1
kind: Secret
metadata:
  namespace: sc-kubernetes
  name: mysql-secret
data:
  mysql.username: cm9vdAo=
  mysql.password: MTIzNDU2Cg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: sc-kubernetes
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      namespace: sc-kubernetes
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          ports:
            - containerPort: 9000
          image: registry.cn-hangzhou.aliyuncs.com/james-k8s/order-service:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: MYSQL-HOST
              value: "mysql-nfs.default"
            - name: MYSQL-USERNAME
              valueFrom:
                secretKeyRef:
                  key: mysql.username
                  name: mysql-secret
            - name: MYSQL-PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql.password
                  name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sc-kubernetes
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: order-service-ingress
  namespace: sc-kubernetes
spec:
  rules:
    - host: order.api.ingress.com
      http:
        paths:
          - backend:
              serviceName: order-service
              servicePort: 9000