server:
  port: 9000
spring:
  application:
    name: @artifactId@
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
  redis:
    host: ${REDIS-HOST}
    port: 6379
    password: ${REDIS-PASSWORD}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL-HOST}:3306/sc-article?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL-USERNAME}
    password: ${MYSQL-PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: debug
mybatis-plus:
  global-config:
    banner: off
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false