apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      name: nacos
      labels:
        app: nacos
        tier: mysql
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:1.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8848
          env:
            - name: MODE
              value: "standalone"
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MYSQL_SERVICE_HOST
              value: 192.168.2.107
            - name: MYSQL_SERVICE_PORT
              value: "31036"
            - name: MYSQL_SERVICE_DB_NAME
              value: nacos-config
            - name: MYSQL_SERVICE_DB_PARAM
              value: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true"
            - name: MYSQL_SERVICE_USER
              value: "root"
            - name: MYSQL_SERVICE_PASSWORD
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  selector:
    app: nacos
  ports:
    - port: 8848
      targetPort: 8848
      nodePort: 31048
  type: NodePort